## Трухманов Е.К. Тетрадь №2 ИКБО-12-22

# 1.1. Теоретический материал – Библиотека NumPy


In [ ]:
NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
 pip install numpy
Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
 import numpy as np
Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
ndarray.ndim - число измерений (чаще их называют "оси") массива.
ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html


# 1.2.1 Пример

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [3]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2 Пример

Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [8]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


# 1.2.3 Пример

Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [9]:
import numpy as np
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0009613825919432273 0.9976943348395177 0.4627407690957495


# 1.2.4 Пример

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [18]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [20]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 1.2.6 Пример

Отсортировать массив.

In [23]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [46]:
import numpy as np
arr = np.full((8, 8), 1)

arr[1::2, ::2] = 0
arr[::2, 1::2] = 0
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [52]:
import numpy as np
x = np.full((5, 5), np.arange(5))

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.

In [55]:
import numpy as np
arr = np.random.random((3, 3, 3))

print(arr)

[[[0.03639337 0.13236977 0.60033527]
  [0.0551342  0.40322549 0.59072044]
  [0.74143698 0.19491367 0.59794079]]

 [[0.35002657 0.32310395 0.21105263]
  [0.66549952 0.00513203 0.15156304]
  [0.49048796 0.13185507 0.58510745]]

 [[0.98947637 0.74715135 0.50302987]
  [0.64812423 0.83335446 0.4231677 ]
  [0.51499618 0.08917666 0.37912392]]]


# 1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.

In [65]:
import numpy as np
n,m = int(input("Введите число строк: ")), int(input("Введите число столбцов: "))
arr = np.full((n, m), 1)
arr[1:n-1, 1:m-1] = 0

print(arr)

Введите число строк: 5
Введите число столбцов: 8
[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


# 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [9]:
import numpy as np
x = [4, 6, 3, 0, 10]
print(np.sort(x)[-1::-1])

[10  6  4  3  0]


# 1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность.

In [16]:
import numpy as np
x = np.full((5, 6), 1)
print(x)
print("Размерность: ", np.shape(x))
print("Кол-во элементов: ", np.size(x))
#print("Размер каждого элемента: ", np.itemsize(x))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Размерность:  (5, 6)
Кол-во элементов:  30


# 2.1. Теоретический материал – Библиотека Pandas

Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком- либо формате. Кроме того, часто требуется получить данные из нескольких источников.
Библиотека pandas – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то pandas – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:
 pip install pandas
Для импорта библиотеки используйте команду:
import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.
Series – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
DataFrame – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

# 2.2.1 Пример

 Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [45]:
import pandas as pd
import numpy as np
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


# 2.2.2 Пример

Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [11]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0], '\n')
print(s2[3:])

1
5 

3    2
4    1
dtype: int64


# 2.2.3 Пример

Создайте новый фрейм данных.

In [14]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [20]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

Пронализировать характеристики фрейма данных.

In [31]:
dataframe.head(2)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [33]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [34]:
dataframe.shape

(1313, 6)

In [35]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6 Пример

Выберите индивидуальные данные или срезы фрейма данных.

In [36]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [40]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

Найдите Евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [2]:
import numpy as np
a, b = [3, 1], [10, 5]
d = np.sqrt(pow(a[0] - b[0], 2) + pow(a[1] - b[1], 2))
print(d)

8.06225774829855


# 2.3.2 Задание

Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [9]:
import pandas as pd
url = 'https://data.wa.gov/api/views/f6w7-q2d2/rows.csv'
data = pd.read_csv(url)

data = data[:15000:]

(15000, 17)

# 2.3.3 Задание

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [12]:
data.head(3)

VIN (1-10)     County  ...        Electric Utility 2020 Census Tract
0  5YJ3E1EA8J  San Diego  ...                     NaN      6.073019e+09
1  3FA6P0PU7H   Sedgwick  ...                     NaN      2.017301e+10
2  1N4AZ0CP8D  Snohomish  ...  PUGET SOUND ENERGY INC      5.306105e+10

[3 rows x 17 columns]

In [13]:
data.tail(3)

VIN (1-10)  ... 2020 Census Tract
14997  1N4AZ0CP9F  ...      5.303300e+10
14998  5YJ3E1EB2J  ...      5.300900e+10
14999  1G1RA6S58J  ...      5.301104e+10

[3 rows x 17 columns]

In [14]:
data.shape

(15000, 17)

In [15]:
data.describe()

Postal Code    Model Year  ...  DOL Vehicle ID  2020 Census Tract
count  14999.000000  15000.000000  ...    1.500000e+04       1.499900e+04
mean   98131.759051   2019.136467  ...    2.020315e+08       5.298255e+10
std     2908.511345      2.963201  ...    9.263014e+07       1.486474e+09
min     6371.000000   1999.000000  ...    1.090490e+05       6.029005e+09
25%    98052.000000   2017.000000  ...    1.507904e+08       5.303301e+10
50%    98118.000000   2020.000000  ...    1.951234e+08       5.303303e+10
75%    98371.000000   2022.000000  ...    2.240091e+08       5.305307e+10
max    99403.000000   2023.000000  ...    4.792548e+08       5.503103e+10

[8 rows x 7 columns]

In [16]:
data.iloc[10:21]

VIN (1-10)  ... 2020 Census Tract
10  5YJ3E1EA4J  ...      5.305794e+10
11  5YJ3E1EBXL  ...      5.306105e+10
12  5YJ3E1EA9J  ...      5.303303e+10
13  5YJSA1S29F  ...      5.306105e+10
14  5YJ3E1EAXK  ...      5.306701e+10
15  KNAGV4LD3H  ...      5.303509e+10
16  KNDJP3AE8H  ...      5.303509e+10
17  1N4AZ1CP8K  ...      5.306105e+10
18  1FADP5CU1D  ...      5.306105e+10
19  7SAYGDEE2N  ...      5.307500e+10
20  1N4AZ1CP7J  ...      5.306701e+10

[11 rows x 17 columns]

In [18]:
data[data['Electric Range'] >= 200].head(5)

VIN (1-10)       County  ...        Electric Utility 2020 Census Tract
0  5YJ3E1EA8J    San Diego  ...                     NaN      6.073019e+09
4  5YJ3E1EA7K    Snohomish  ...  PUGET SOUND ENERGY INC      5.306105e+10
5  1G1FZ6S07L  Walla Walla  ...              PACIFICORP      5.307192e+10
6  KNDCC3LG1L    Snohomish  ...  PUGET SOUND ENERGY INC      5.306104e+10
8  5YJ3E1EA1L    Snohomish  ...  PUGET SOUND ENERGY INC      5.306105e+10

[5 rows x 17 columns]

# 3.1. Теоретический материал – Работа с числовыми данными

    Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, $529 392 продаж).
    Нормализация данных — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
    Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.
    На практике наиболее распространены следующие методы нормализации признаков:
    * Минимакс – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения соответствуют 0 и 1 соответственно;
    * Z-масштабирование данных на основе среднего значения и стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.
    При масштабировании данных мы будем использовать одну из популярных библиотек машинного обучения Scikit-learn. Библиотека содержит пакет sklearn.preprocessing, который предоставляет широкие возможности для нормализации данных. Следует отметить, что в целом алгоритмы обучения выигрывают от стандартизации набора данных.

# 3.2.1. Пример

Прошкалируйте числовой признак в диапазон между двумя значениями.

In [1]:
import numpy as np
from sklearn import preprocessing

# Создаем признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

# Создаем шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак

scaled_feature




array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2. Пример

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [8]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

#Создать шкалировщик
scaler = preprocessing.StandardScaler()

#Преобразовать признак
standard = scaler.fit_transform(x)

#показать признак
standard

print("Среднее:", round(standard.mean()))
print("Стандартное отклонение:", standard.std())

Среднее: 0
Стандартное отклонение: 1.0


# 3.2.3. Пример

Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                      'B':[103.02,107.26,110.35,114.23,114.68],
                      'C':['big','small','big','small','small']}) Необходимо масштабировать его числовые столбцы.

In [9]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']}) 

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.2 Задание

Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [19]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
data = pd.read_csv(url)

# Минимакс преобразование
min_max_scaler = MinMaxScaler()
data[['sepal_length_cm']] = min_max_scaler.fit_transform(data[['sepal_length_cm']])

# Z-масштабирование
z_scaler = preprocessing.StandardScaler()
data[['sepal_width_cm']] = z_scaler.fit_transform(data[['sepal_width_cm']])

data

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]